### ISSUE TITLE
Could not reliably determine the server's fully qualified domain name, using <container ip>. Set the 'ServerName' directive globally to suppress this message

### ISSUE THREAD

**Issue by 89ece6d9e021e** [ubc/mediawiki-docker#11]
Hello Guys,

do you know something about this kind of problem?

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.9. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.9. Set the 'ServerName' directive globally to suppress this message
[Mon Mar 25 14:18:13.426707 2019] [mpm_prefork:notice] [pid 17] AH00163: Apache/2.4.25 (Debian) PHP/7.1.27 configured -- resuming normal operations
[Mon Mar 25 14:18:13.426763 2019] [core:notice] [pid 17] AH00094: Command line: '/usr/sbin/apache2 -e info -D FOREGROUND'
```

Below is my docker-compose configuration. Maybe I'm doing something wrong.

```
  mediaWiki:
    image: ubcctlt/mediawiki
    container_name: wiki
    restart: always
    environment:
      - MEDIAWIKI_SITE_SERVER=http://wiki.my-domain.com
      - MEDIAWIKI_SITE_NAME=random name
      - MEDIAWIKI_ADMIN_PASS=admin123
      - MEDIAWIKI_UPDATE=true
      - MEDIAWIKI_DB_TYPE=postgres
      - MEDIAWIKI_DB_HOST=172.18.0.8
      - MEDIAWIKI_DB_USER=admin
      - MEDIAWIKI_DB_PASSWORD=admin123
      - MEDIAWIKI_DB_NAME=wiki
    volumes:
      - /docker/www/wiki/html:/var/www/html
      - /docker/www/wiki/html/cache:/var/www/html/cache
      - /docker/www/wiki/cache:/var/cache
```

BTW. there is an issue with cache directory. It doesn't exist. This is a reason why I'm mapping it.
