### ISSUE TITLE
ProxyPass URL must be absolute!: restbase-is-not-specified/localhost/v1

### ISSUE THREAD

**Issue by ModestTG** [ubc/mediawiki-docker#21]
Hello,

As the title says, I get an error because the default `$RESTBASE_URL` environment variable defaults to none (per the documentation), or in this case `restbase-is-not-specified`. Because of this, I am not able to start the container. I'm not seeing anywhere where it says that restbase needs to be installed for the container to work, and if so, shouldn't restbase be included into the container with a proper default for the EV?

Docker-Compose file:
```
mediawiki:
    image: ubcctlt/mediawiki:latest
    container_name: MediaWiki
    restart: never
    depends_on:
      - mysql
    networks:
      - default
      - traefik_proxy
    ports:
      - "8092:8080"
    volumes:
      - "/mnt/container_data/mediawiki/data:/data"
    env_file:
      - ./envs/mediawiki.env
```

`restart:` is set to `never` because this failure is causing the container to continuously restart.

log output:
```
Done in 0.9 s.
AH00526: Syntax error on line 30 of /etc/apache2/mediawiki.conf:
ProxyPass URL must be absolute!: restbase-is-not-specified/localhost/v1
Action '-e info -D FOREGROUND' failed.
The Apache error log may have more information.
```

environment variables:
```
MEDIAWIKI_SITE_SERVER=http://[redacted]:8080
MEDIAWIKI_SITE_NAME="EW Homelab Services Wiki"
MEDIAWIKI_SITE_LANG=en
MEDIAWIKI_ADMIN_USER=eweishaar
MEDIAWIKI_ADMIN_PASS=[redacted]
MEDIAWIKI_UPDATE=true
MEDIAWIKI_DB_TYPE=mysql
MEDIAWIKI_DB_HOST=[redacted]
MEDIAWIKI_DB_PORT=3306
MEDIAWIKI_DB_USER=eweishaar
MEDIAWIKI_DB_PASSWORD=[redacted]
MEDIAWIKI_DB_NAME=mediawiki_db
```

Let me know if I am missing something blatantly obvious or if you need more information
